- name: Install Docker on Debian 11 & start the containers
  become: yes
  hosts: host1

  vars:
    client_image: sgumbe/yolo-latest:1.1.0
    backend_image: sgumbe/yolo-latest:1.2.0
    app_folder: /opt/yolo
    compose_file_src: /home/gumbe12/WEEK9-ANSIBLE/YOLO/docker-compose.yml
    compose_file_dest: "{{ app_folder }}/docker-compose.yml"

  tasks:
    - name: Update the cache
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install packages on Debian-based systems
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        update_cache: yes

    - name: Add Docker official GPG key to the system.
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker repository to the system
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bullseye stable
        state: present

    - name: Update the cache
      apt:
        update_cache: yes

    - name: Install Docker-related packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - docker-compose
        update_cache: yes

    - name: Install the Docker module for Python, required by Ansible
      pip:
        name: docker

    - name: Pull the client image
      community.docker.docker_image:
        name: "{{ client_image }}"
        source: pull

    - name: Pull the backend image
      community.docker.docker_image:
        name: "{{ backend_image }}"
        source: pull

    - name: Create app folder
      file:
        path: "{{ app_folder }}"
        state: directory

    - name: Create backend folder
      file:
        path: "{{ app_folder }}/backend"
        state: directory

    - name: Create app directory for client container
      docker_container:
        name: yolo-client
        image: "{{ client_image }}"
        command: "mkdir -p /app"
        state: started
        volumes:
          - "{{ app_folder }}/client:/app"
        restart_policy: always

    - name: Create app directory for backend container
      docker_container:
        name: yolo-backend
        image: "{{ backend_image }}"
        command: "mkdir -p /app"
        state: started
        volumes:
          - "{{ app_folder }}/backend:/app"
        restart_policy: always

    - name: Create client directories
      file:
        path: "{{ app_folder }}/client/{{ item }}"
        state: directory
      loop:
        - src

    - name: Copy backend Dockerfile
      copy:
        src: /home/gumbe12/WEEK9-ANSIBLE/YOLO/backend/Dockerfile
        dest: "{{ app_folder }}/backend/Dockerfile"

    - name: Copy backend environment file
      copy:
        src: /home/gumbe12/WEEK9-ANSIBLE/YOLO/backend/.env
        dest: "{{ app_folder }}/backend/.env"

    - name: Copy docker-compose file to target hosts
      copy:
        src: "{{ compose_file_src }}"
        dest: "{{ compose_file_dest }}"

    - name: Start Docker Compose services
      command: docker-compose up -d
      args:
        chdir: "{{ app_folder }}"

    - name: Wait for containers to start
      wait_for:
        host: localhost
        port: 3000
        delay: 5
        timeout: 60
        state: started

    - name: Check if containers started successfully
      assert:
        that: "'yolo-client' in docker_output.stdout and 'yolo-backend' in docker_output.stdout"
        fail_msg: "Containers failed to start."

    - name: Print Docker container status
      command: docker ps -a
      register: docker_output

    - name: Verify backend container status
      assert:
        that:
          - "'yolo-backend' in docker_output.stdout"
        fail_msg: "Backend container is not running."

    - name: Verify client container status
      assert:
        that:
          - "'yolo-client' in docker_output.stdout"
        fail_msg: "Client container is not running."
